version: 0.0
os: linux
files:
  - source: metadata/conf/context.xml
    destination: /tomcat/apache-tomcat-4.1.40/webapps/buptlab/META-INF
  - source: lib/mysql-connector-java-5.1.49.jar
    destination: /tomcat/apache-tomcat-4.1.40/common/lib
  - source: lib/jta.jar
    destination: /tomcat/apache-tomcat-4.1.40/common/lib
  - source: buptlab.war
    destination: /tomcat/apache-tomcat-4.1.40/webapps
hooks:
  AfterInstall:
    - location: scripts/change_permissions.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
